name: Build all

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      release:
        description: Publish GitHub release
        type: boolean
        required: false
        default: false
      nuget:
        description: Publish on nuget.org
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug build
        type: boolean
        required: false
        default: false

jobs:
  linux_arm:
    name: Linux arm (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm

  linux_arm_musl:
    name: Linux arm (musl)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm
      target_environment: musl

  linux_arm64:
    name: Linux arm64 (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm64

  linux_arm64_musl:
    name: Linux arm64 (musl)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm64
      target_environment: musl

  linux_x64:
    name: Linux x64 (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: x64

  linux_x64_musl:
    name: Linux x64 (musl)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: x64
      target_environment: musl

  linux_riscv64:
    name: Linux riscv64 (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: riscv64

  linux_riscv64_musl:
    name: Linux riscv64 (musl)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: riscv64
      target_environment: musl

  nuget:
    name: Build NuGet package
    if: github.event.inputs.nuget == 'true'
    runs-on: ubuntu-latest
    needs:
      - linux_arm
      - linux_arm_musl
      - linux_arm64
      - linux_arm64_musl
      - linux_x64
      - linux_x64_musl
      - linux_riscv64
      - linux_riscv64_musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: nuget
      - name: Install NuGet CLI
        shell: bash
        run: |
          dotnet tool install --global NuGet.CommandLine
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      - name: Prepare header files
        run: |
          mkdir -p nuget/include/pdfium
          cp -r nuget/pdfium-linux-x64/include/* nuget/include/pdfium/
        shell: bash
      - name: Define properties
        shell: bash
        run: |
          VERSION="$VERSION"
          BRANCH="${GITHUB_REF#refs/heads/}"
          COMMIT="${GITHUB_SHA}"
          RELEASE_NOTES="${{github.server_url}}/${{github.repository}}/releases"
          $RELEASE && RELEASE_NOTES+="/tag/$BRANCH"
          echo "NUSPEC_PROPERTIES=version=$VERSION;branch=$BRANCH;commit=$COMMIT;releaseNotes=$RELEASE_NOTES" >> "$GITHUB_ENV"
        env:
          VERSION: ${{ github.event.inputs.version || '0.0.0.0' }}
          RELEASE: ${{ github.event.inputs.release }}
          BRANCH: ${{ github.event.inputs.branch }}
      - name: Pack
        shell: bash
        run: |
          NUSPEC=nuget/bblanchon.PDFium.Linux.nuspec
          echo "::group::$NUSPEC"
          nuget pack "$NUSPEC" -p "$NUSPEC_PROPERTIES"
          echo "::endgroup::"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NuGet packages
          path: '*.nupkg'
      - name: Push to nuget.org
        if: env.NUGET_API_KEY && startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version && github.event.inputs.nuget == 'true'
        run: nuget push -Source nuget.org -ApiKey ${{ secrets.NUGET_API_KEY }} *.nupkg
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY  }}
    env:
      RELEASE: ${{ github.event.inputs.release }}

  publish:
    name: Publish Release
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
      tagname: ${{ github.event.inputs.branch }}
    if: startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version && github.event.inputs.release == 'true'
    runs-on: ubuntu-latest
    needs:
      - linux_arm
      - linux_arm_musl
      - linux_arm64
      - linux_arm64_musl
      - linux_x64
      - linux_x64_musl
      - linux_riscv64
      - linux_riscv64_musl
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create tarballs
        run: |
          for DIR in pdfium-*; do
            echo "::group::$DIR"
            (cd $DIR && tar czf ../$DIR.tgz *)
            echo "::endgroup::"
        shell: bash
      - name: Write release body
        run: echo "This version was built with branch `$BRANCH` of PDFium" > RELEASE.md
        env:
          BRANCH: ${{ github.event.inputs.branch }}
      - name: Get changes
        continue-on-error: true
        run: |
          CURRENT_REV=$BRANCH
          PREVIOUS_REV=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name")
          git clone -b "$BRANCH" https://pdfium.googlesource.com/pdfium.git
          cat <<END >> RELEASE.md
          ### Changes
          Commits between \`$PREVIOUS_REV\` and \`$CURRENT_REV\`:
          END
          git -C "pdfium" log origin/${PREVIOUS_REV}.. --pretty=format:'* [%s](https://pdfium.googlesource.com/pdfium/+/%H)' >> RELEASE.md
        env:
          BRANCH: ${{ github.event.inputs.branch }}
      - name: Generate artifacts checksums
        id: hash
        run: echo "hashes=$(sha256sum pdfium-*.tgz | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: Attest build provenance
        id: provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: pdfium-*.tgz
      - name: Rename provenance file
        run: mv "${{ steps.provenance.outputs.bundle-path }}" pdfium-attestation.json
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          immutableCreate: true
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PDFium ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.branch }}
          artifacts: pdfium-*.tgz, pdfium-attestation.json
