name: Build all

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      release:
        description: Publish GitHub release
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug build
        type: boolean
        required: false
        default: false

jobs:
  linux_arm:
    name: Linux arm (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm

  linux_arm_musl:
    name: Linux arm (musl)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm
      target_environment: musl

  linux_arm64:
    name: Linux arm64 (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm64

  linux_arm64_musl:
    name: Linux arm64 (musl)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: arm64
      target_environment: musl

  linux_x64:
    name: Linux x64 (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: x64

  linux_riscv64:
    name: Linux riscv64 (glibc)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_cpu: riscv64

  publish:
    name: Publish Release
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
      tagname: ${{ github.event.inputs.branch }}
    if: github.event.inputs.version && github.event.inputs.release == 'true'
    runs-on: ubuntu-latest
    needs:
      - linux_arm
      - linux_arm_musl
      - linux_arm64
      - linux_arm64_musl
      - linux_x64
      - linux_riscv64
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create tarballs
        run: |
          for DIR in pdfium-*; do
            echo "::group::$DIR"
            (cd $DIR && tar czf ../$DIR.tgz *)
            echo "::endgroup::"
          done
        shell: bash
      - name: Write release body
        run: echo "This version was built with branch `$BRANCH` of PDFium" > RELEASE.md
        env:
          BRANCH: ${{ github.event.inputs.branch }}
      - name: Get changes
        continue-on-error: true
        run: |
          CURRENT_REV=$BRANCH
          PREVIOUS_REV=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name")
          git clone -b "$BRANCH" https://pdfium.googlesource.com/pdfium.git
          cat <<END >> RELEASE.md
          ### Changes
          Commits between \`$PREVIOUS_REV\` and \`$CURRENT_REV\`:
          END
          git -C "pdfium" log origin/${PREVIOUS_REV}.. --pretty=format:'* [%s](https://pdfium.googlesource.com/pdfium/+/%H)' >> RELEASE.md
        env:
          BRANCH: ${{ github.event.inputs.branch }}
      - name: Generate artifacts checksums
        id: hash
        run: echo "hashes=$(sha256sum pdfium-*.tgz | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: Attest build provenance
        id: provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: pdfium-*.tgz
      - name: Rename provenance file
        run: mv "${{ steps.provenance.outputs.bundle-path }}" pdfium-attestation.json
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          immutableCreate: true
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PDFium ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.branch }}
          artifacts: pdfium-*.tgz, pdfium-attestation.json
